//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Fx.Portability.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Fx.Portability.Resources.LocalizedStrings", typeof(LocalizedStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias cannot be equal to a target name: &apos;{0}&apos;.
        /// </summary>
        internal static string AliasCannotBeEqualToTargetNameError {
            get {
                return ResourceManager.GetString("AliasCannotBeEqualToTargetNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single mappings between name and alias are supported.  The following aliases are invalid: {0}.
        /// </summary>
        internal static string AliasMappedToMultipleNamesInvalidAliases {
            get {
                return ResourceManager.GetString("AliasMappedToMultipleNamesInvalidAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An alias should be separated from names by &apos;{0}&apos;.
        /// </summary>
        internal static string AliasShouldBeSeparated {
            get {
                return ResourceManager.GetString("AliasShouldBeSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing compatibility.
        /// </summary>
        internal static string AnalyzingCompatibility {
            get {
                return ResourceManager.GetString("AnalyzingCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Version={1}, Culture={2}, PublicKeyToken={3}.
        /// </summary>
        internal static string AssemblyReferenceInformation {
            get {
                return ResourceManager.GetString("AssemblyReferenceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to the path once a query has begun.
        /// </summary>
        internal static string CannotAddToRunningQueryPath {
            get {
                return ResourceManager.GetString("CannotAddToRunningQueryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given filename [{0}] has a different extension than the output format extension. Changed extension &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string ChangingFileExtension {
            get {
                return ResourceManager.GetString("ChangingFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computing report..
        /// </summary>
        internal static string ComputingReport {
            get {
                return ResourceManager.GetString("ComputingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write report to directory &apos;{0}&apos; with file name &apos;{1}&apos; and extension &apos;{2}&apos;..
        /// </summary>
        internal static string CouldNotWriteReport {
            get {
                return ResourceManager.GetString("CouldNotWriteReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate alias: &apos;{0}&apos;.
        /// </summary>
        internal static string DuplicateAliasError {
            get {
                return ResourceManager.GetString("DuplicateAliasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework.
        /// </summary>
        internal static string FrameworkNameHeader {
            get {
                return ResourceManager.GetString("FrameworkNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, FileVersion:{1}.
        /// </summary>
        internal static string FullAssemblyIdentity {
            get {
                return ResourceManager.GetString("FullAssemblyIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to specify a version, please use the following format with the &apos;-targets&apos; option:
        ///	(Target Name), Version=(Version).
        /// </summary>
        internal static string HowToSpecifyVersion {
            get {
                return ResourceManager.GetString("HowToSpecifyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unknown error attempting to reach the service.  Please try again..
        /// </summary>
        internal static string HttpExceptionMessage {
            get {
                return ResourceManager.GetString("HttpExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying assemblies to scan..
        /// </summary>
        internal static string IdentifyAssembliesToScan {
            get {
                return ResourceManager.GetString("IdentifyAssembliesToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid assembly..
        /// </summary>
        internal static string InvalidAssembly {
            get {
                return ResourceManager.GetString("InvalidAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled breaking change parse state: {0}.
        /// </summary>
        internal static string InvalidBreakingChangeParserState {
            get {
                return ResourceManager.GetString("InvalidBreakingChangeParserState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category detected: {0}.
        /// </summary>
        internal static string InvalidCategoryDetected {
            get {
                return ResourceManager.GetString("InvalidCategoryDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        internal static string InvalidDataMessage {
            get {
                return ResourceManager.GetString("InvalidDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed map: {0}.
        /// </summary>
        internal static string MalformedMap {
            get {
                return ResourceManager.GetString("MalformedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member should be defined on a type.
        /// </summary>
        internal static string MemberShouldBeDefinedOnTypeException {
            get {
                return ResourceManager.GetString("MemberShouldBeDefinedOnTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid endpoint.
        /// </summary>
        internal static string MustBeValidEndpoint {
            get {
                return ResourceManager.GetString("MustBeValidEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files were found to upload..
        /// </summary>
        internal static string NoFilesAvailableToUpload {
            get {
                return ResourceManager.GetString("NoFilesAvailableToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource was not found for {0} {1}.
        /// </summary>
        internal static string NotFoundException {
            get {
                return ResourceManager.GetString("NotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists and will be overwritten..
        /// </summary>
        internal static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0}/{1} files..
        /// </summary>
        internal static string ProcessedFiles {
            get {
                return ResourceManager.GetString("ProcessedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0} items..
        /// </summary>
        internal static string ProcessedItems {
            get {
                return ResourceManager.GetString("ProcessedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must only contain letters or digits.
        /// </summary>
        internal static string ProductInformationInvalidArgument {
            get {
                return ResourceManager.GetString("ProductInformationInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Done].
        /// </summary>
        internal static string ProgressReportDone {
            get {
                return ResourceManager.GetString("ProgressReportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Failed].
        /// </summary>
        internal static string ProgressReportFailed {
            get {
                return ResourceManager.GetString("ProgressReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy authentication required to access: {0}. To resolve, try setting proxy in config.json..
        /// </summary>
        internal static string ProxyAuthenticationRequiredMessage {
            get {
                return ResourceManager.GetString("ProxyAuthenticationRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to service is too large. Send fewer assemblies for analysis. Content length: {0} bytes.
        /// </summary>
        internal static string RequestTooLargeMessage {
            get {
                return ResourceManager.GetString("RequestTooLargeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving output formats..
        /// </summary>
        internal static string RetrievingOutputFormats {
            get {
                return ResourceManager.GetString("RetrievingOutputFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving targets.
        /// </summary>
        internal static string RetrievingTargets {
            get {
                return ResourceManager.GetString("RetrievingTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: A newer version of the application is available. Please update to the latest version to continue using this service.
        /// </summary>
        internal static string ServerEndpointDeprecated {
            get {
                return ResourceManager.GetString("ServerEndpointDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The service endpoint has been deprecated. Please update the application to the latest version..
        /// </summary>
        internal static string ServerEndpointMovedPermanently {
            get {
                return ResourceManager.GetString("ServerEndpointMovedPermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported: {0}+.
        /// </summary>
        internal static string SupportedOn {
            get {
                return ResourceManager.GetString("SupportedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string TargetInformationGroups {
            get {
                return ResourceManager.GetString("TargetInformationGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets.
        /// </summary>
        internal static string Targets {
            get {
                return ResourceManager.GetString("Targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel output format supports up to {0} targets for analysis at a time..
        /// </summary>
        internal static string TooManyTargetsMessage {
            get {
                return ResourceManager.GetString("TooManyTargetsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint requires an authentication token..
        /// </summary>
        internal static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.  Please make sure you the most up-to-date version.
        /// </summary>
        internal static string UnknownBadRequestMessage {
            get {
                return ResourceManager.GetString("UnknownBadRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unknown error code from the service: &apos;{0}&apos;.  Please make sure you have the most up-to-date version..
        /// </summary>
        internal static string UnknownErrorCodeMessage {
            get {
                return ResourceManager.GetString("UnknownErrorCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown output format: &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownResultFormat {
            get {
                return ResourceManager.GetString("UnknownResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown target &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownTarget {
            get {
                return ResourceManager.GetString("UnknownTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionHeader {
            get {
                return ResourceManager.GetString("VersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing {0} report.
        /// </summary>
        internal static string WritingReport {
            get {
                return ResourceManager.GetString("WritingReport", resourceCulture);
            }
        }
    }
}
