//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Fx.Portability.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Fx.Portability.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias cannot be equal to a target name: &apos;{0}&apos;.
        /// </summary>
        public static string AliasCanotBeEqualToTargetNameError {
            get {
                return ResourceManager.GetString("AliasCanotBeEqualToTargetNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single mappings between name and alias are supported.  The following aliases are invalid: {0}.
        /// </summary>
        public static string AliasMappedToMultipleNamesInvalidAliases {
            get {
                return ResourceManager.GetString("AliasMappedToMultipleNamesInvalidAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Grouped Targets:.
        /// </summary>
        public static string AvailableGroupedTargets {
            get {
                return ResourceManager.GetString("AvailableGroupedTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given filename [{0}] has a different extension than the output format extension. Changed extension &quot;{1}&quot; to &quot;{2}&quot;..
        /// </summary>
        public static string ChangingFileExtension {
            get {
                return ResourceManager.GetString("ChangingFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computing report..
        /// </summary>
        public static string ComputingReport {
            get {
                return ResourceManager.GetString("ComputingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting assembly references..
        /// </summary>
        public static string DetectingAssemblyReferences {
            get {
                return ResourceManager.GetString("DetectingAssemblyReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate alias: &apos;{0}&apos;.
        /// </summary>
        public static string DuplicateAliasError {
            get {
                return ResourceManager.GetString("DuplicateAliasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, FileVersion:{1}.
        /// </summary>
        public static string FullAssemblyIdentity {
            get {
                return ResourceManager.GetString("FullAssemblyIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to specify a version, please use the following format with the &apos;-targets&apos; option:
        ///	(Target Name), Version=(Version).
        /// </summary>
        public static string HowToSpecifyVersion {
            get {
                return ResourceManager.GetString("HowToSpecifyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unknown error attempting to reach the service.  Please try again..
        /// </summary>
        public static string HttpExceptionMessage {
            get {
                return ResourceManager.GetString("HttpExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying assemblies to scan..
        /// </summary>
        public static string IdentifyAssembliesToScan {
            get {
                return ResourceManager.GetString("IdentifyAssembliesToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        public static string InvalidDataMessage {
            get {
                return ResourceManager.GetString("InvalidDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name: &apos;{0}&apos;.
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed map: {0}.
        /// </summary>
        public static string MalformedMap {
            get {
                return ResourceManager.GetString("MalformedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member should be defined on a type.
        /// </summary>
        public static string MemberShouldBeDefinedOnTypeException {
            get {
                return ResourceManager.GetString("MemberShouldBeDefinedOnTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files were found to upload..
        /// </summary>
        public static string NoFilesAvailableToUpload {
            get {
                return ResourceManager.GetString("NoFilesAvailableToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource was not found..
        /// </summary>
        public static string NotFoundException {
            get {
                return ResourceManager.GetString("NotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        public static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced output file &quot;{0}&quot;.
        /// </summary>
        public static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0}/{1} files..
        /// </summary>
        public static string ProcessedFiles {
            get {
                return ResourceManager.GetString("ProcessedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0} items..
        /// </summary>
        public static string ProcessedItems {
            get {
                return ResourceManager.GetString("ProcessedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must only contain letters or digits.
        /// </summary>
        public static string ProductInformationInvalidArgument {
            get {
                return ResourceManager.GetString("ProductInformationInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving targets..
        /// </summary>
        public static string RetrievingTargets {
            get {
                return ResourceManager.GetString("RetrievingTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending data to service..
        /// </summary>
        public static string SendingDataToService {
            get {
                return ResourceManager.GetString("SendingDataToService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: A newer version of the application is available. Please update to the latest version to continue using this service.
        /// </summary>
        public static string ServerEndpointDeprecated {
            get {
                return ResourceManager.GetString("ServerEndpointDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The service endpoint has been deprecated. Please update the application to the latest version..
        /// </summary>
        public static string ServerEndpointMovedPermanently {
            get {
                return ResourceManager.GetString("ServerEndpointMovedPermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported: {0}+.
        /// </summary>
        public static string SupportedOn {
            get {
                return ResourceManager.GetString("SupportedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string TargetInformationGroups {
            get {
                return ResourceManager.GetString("TargetInformationGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint requires an authentication token..
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.  Please make sure you the most up-to-date version.
        /// </summary>
        public static string UnknownBadRequestMessage {
            get {
                return ResourceManager.GetString("UnknownBadRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unknown error code from the service: &apos;{0}&apos;.  Please make sure you have the most up-to-date version..
        /// </summary>
        public static string UnknownErrorCodeMessage {
            get {
                return ResourceManager.GetString("UnknownErrorCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file: &apos;{0}&apos;.
        /// </summary>
        public static string UnknownFile {
            get {
                return ResourceManager.GetString("UnknownFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown target &apos;{0}&apos;.
        /// </summary>
        public static string UnknownTarget {
            get {
                return ResourceManager.GetString("UnknownTarget", resourceCulture);
            }
        }
    }
}
