//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPortVS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiPortVS.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Privacy Statement.
        /// </summary>
        public static string AboutPrivacy {
            get {
                return ResourceManager.GetString("AboutPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Tool.
        /// </summary>
        public static string AboutTool {
            get {
                return ResourceManager.GetString("AboutTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis failed..
        /// </summary>
        public static string AnalysisFailed {
            get {
                return ResourceManager.GetString("AnalysisFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Files.
        /// </summary>
        public static string AssemblyFiles {
            get {
                return ResourceManager.GetString("AssemblyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        public static string AssemblyHeader {
            get {
                return ResourceManager.GetString("AssemblyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to summary.
        /// </summary>
        public static string BackToSummary {
            get {
                return ResourceManager.GetString("BackToSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a reference to the Output window general pane..
        /// </summary>
        public static string CannotReferenceOutputWindow {
            get {
                return ResourceManager.GetString("CannotReferenceOutputWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save report at &apos;{0}&apos;..
        /// </summary>
        public static string CannotSaveReport {
            get {
                return ResourceManager.GetString("CannotSaveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot view report because browser service is null..
        /// </summary>
        public static string CannotViewReport {
            get {
                return ResourceManager.GetString("CannotViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to refresh platforms.
        /// </summary>
        public static string ClickToRefreshPlatforms {
            get {
                return ResourceManager.GetString("ClickToRefreshPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft (R) .NET Portability Analyzer {0}
        ///Copyright (C) Microsoft Corporation. All rights reserved..
        /// </summary>
        public static string CopyrightFormat {
            get {
                return ResourceManager.GetString("CopyrightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default output name.
        /// </summary>
        public static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default output directory.
        /// </summary>
        public static string DefaultOutputDirectory {
            get {
                return ResourceManager.GetString("DefaultOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsPageTitle {
            get {
                return ResourceManager.GetString("DetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting package reference info..
        /// </summary>
        public static string ErrorGettingInstalledPackages {
            get {
                return ResourceManager.GetString("ErrorGettingInstalledPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find source line information for {0}..
        /// </summary>
        public static string FailedToFindSourceLines {
            get {
                return ResourceManager.GetString("FailedToFindSourceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate build output files..
        /// </summary>
        public static string FailedToLocateBuildOutputDir {
            get {
                return ResourceManager.GetString("FailedToLocateBuildOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding source line information.
        /// </summary>
        public static string FindingSourceLineInformationFor {
            get {
                return ResourceManager.GetString("FindingSourceLineInformationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-us.
        /// </summary>
        public static string HtmlContentLanguage {
            get {
                return ResourceManager.GetString("HtmlContentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Portability Report.
        /// </summary>
        public static string HtmlReportTitle {
            get {
                return ResourceManager.GetString("HtmlReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid assembly..
        /// </summary>
        public static string InvalidAssembly {
            get {
                return ResourceManager.GetString("InvalidAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid platform {0} selected..
        /// </summary>
        public static string InvalidPlatformSelectedFormat {
            get {
                return ResourceManager.GetString("InvalidPlatformSelectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * {0}.
        /// </summary>
        public static string ListItem {
            get {
                return ResourceManager.GetString("ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing assemblies.
        /// </summary>
        public static string MissingAssembliesPageTitle {
            get {
                return ResourceManager.GetString("MissingAssembliesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string MissingAssemblyStatus {
            get {
                return ResourceManager.GetString("MissingAssemblyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No analyzable assemblies found in {0}..
        /// </summary>
        public static string NoAnalyzableAssemblies {
            get {
                return ResourceManager.GetString("NoAnalyzableAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported on .
        /// </summary>
        public static string NotSupportedOn {
            get {
                return ResourceManager.GetString("NotSupportedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output formats.
        /// </summary>
        public static string OutputFormats {
            get {
                return ResourceManager.GetString("OutputFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: PDB {0} not found..
        /// </summary>
        public static string PdbNotFoundFormat {
            get {
                return ResourceManager.GetString("PdbNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portability Analysis.
        /// </summary>
        public static string PortabilityOutputTitle {
            get {
                return ResourceManager.GetString("PortabilityOutputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended changes.
        /// </summary>
        public static string RecommendedChanges {
            get {
                return ResourceManager.GetString("RecommendedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing output formats....
        /// </summary>
        public static string RefreshingOutputFormats {
            get {
                return ResourceManager.GetString("RefreshingOutputFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing platforms....
        /// </summary>
        public static string RefreshingPlatforms {
            get {
                return ResourceManager.GetString("RefreshingPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory the report was in is not available. It may have been deleted..
        /// </summary>
        public static string ReportDirectoryNotAvailable {
            get {
                return ResourceManager.GetString("ReportDirectoryNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report written to &apos;{0}&apos;.
        /// </summary>
        public static string ReportLocation {
            get {
                return ResourceManager.GetString("ReportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report is not available. It may have been deleted..
        /// </summary>
        public static string ReportNotAvailable {
            get {
                return ResourceManager.GetString("ReportNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Assembly Files.
        /// </summary>
        public static string SelectAssemblyFiles {
            get {
                return ResourceManager.GetString("SelectAssemblyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Source line information for portable pdbs is not currently supported.
        ///        Add the following code to: {0}&apos;s
        ///        project (ie. *.csproj or *.fsproj) and try again.
        ///
        ///        &lt;PropertyGroup&gt;
        ///          &lt;DebugType&gt;Full&lt;/DebugType&gt;
        ///        &lt;/PropertyGroup&gt;.
        /// </summary>
        public static string SourceLineMappingNotSupportedPortablePdb {
            get {
                return ResourceManager.GetString("SourceLineMappingNotSupportedPortablePdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission ID:.
        /// </summary>
        public static string SubmissionId {
            get {
                return ResourceManager.GetString("SubmissionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion: .
        /// </summary>
        public static string Suggestion {
            get {
                return ResourceManager.GetString("Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SummaryHeading {
            get {
                return ResourceManager.GetString("SummaryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Platforms.
        /// </summary>
        public static string TargetPlatforms {
            get {
                return ResourceManager.GetString("TargetPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target platform {0} {1}..
        /// </summary>
        public static string TargetPlatformVersionFormat {
            get {
                return ResourceManager.GetString("TargetPlatformVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets.
        /// </summary>
        public static string Targets {
            get {
                return ResourceManager.GetString("Targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To select platforms, visit Tools-&gt;Options-&gt;.NET Portability Analyzer..
        /// </summary>
        public static string TargetSelectionGuidance {
            get {
                return ResourceManager.GetString("TargetSelectionGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target type.
        /// </summary>
        public static string TargetTypeHeader {
            get {
                return ResourceManager.GetString("TargetTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project was either canceled or could not be built. Please look at the error window for any build errors..
        /// </summary>
        public static string UnableToBuildProject {
            get {
                return ResourceManager.GetString("UnableToBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to contact service.  Try again later..
        /// </summary>
        public static string UnableToContactService {
            get {
                return ResourceManager.GetString("UnableToContactService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load {0}..
        /// </summary>
        public static string UnableToLoad {
            get {
                return ResourceManager.GetString("UnableToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file {0}..
        /// </summary>
        public static string UnableToSaveFileFormat {
            get {
                return ResourceManager.GetString("UnableToSaveFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved assembly.
        /// </summary>
        public static string UnresolvedUsedAssembly {
            get {
                return ResourceManager.GetString("UnresolvedUsedAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used By.
        /// </summary>
        public static string UsedBy {
            get {
                return ResourceManager.GetString("UsedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using default target platforms..
        /// </summary>
        public static string UsingDefaultTargets {
            get {
                return ResourceManager.GetString("UsingDefaultTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing report..
        /// </summary>
        public static string WritingReport {
            get {
                return ResourceManager.GetString("WritingReport", resourceCulture);
            }
        }
    }
}
