//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Fx.Portability.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Fx.Portability.Resources.LocalizedStrings", typeof(LocalizedStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Called .Name on a currently unsupported type definition!.
        /// </summary>
        internal static string CalledNameOnUnsupportedDefinition {
            get {
                return ResourceManager.GetString("CalledNameOnUnsupportedDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Core Assembly can only be set once..
        /// </summary>
        internal static string CoreAssemblyAlreadySet {
            get {
                return ResourceManager.GetString("CoreAssemblyAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find core assembly &apos;{0}&apos; in the list of contracts..
        /// </summary>
        internal static string CoreAssemblyNotFoundInContracts {
            get {
                return ResourceManager.GetString("CoreAssemblyNotFoundInContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find core assembly &apos;{0}&apos; in the list of identities..
        /// </summary>
        internal static string CoreAssemblyNotFoundInIdentities {
            get {
                return ResourceManager.GetString("CoreAssemblyNotFoundInIdentities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting assembly references.
        /// </summary>
        internal static string DetectingAssemblyReferences {
            get {
                return ResourceManager.GetString("DetectingAssemblyReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fell through cases in {0} Type of reference: {1}.
        /// </summary>
        internal static string FellThroughCasesIn {
            get {
                return ResourceManager.GetString("FellThroughCasesIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type reference that we may need to unwrap {0}.
        /// </summary>
        internal static string UnexpectedTypeReference {
            get {
                return ResourceManager.GetString("UnexpectedTypeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file: &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownFile {
            get {
                return ResourceManager.GetString("UnknownFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown IReference &apos;{0}&apos; so we cannot get assembly reference!.
        /// </summary>
        internal static string UnknownIReference {
            get {
                return ResourceManager.GetString("UnknownIReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown Reference Type&gt;.
        /// </summary>
        internal static string UnknownReferenceType {
            get {
                return ResourceManager.GetString("UnknownReferenceType", resourceCulture);
            }
        }
    }
}
