//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Fx.Portability.Reports.Excel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Fx.Portability.Reports.Excel.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name.
        /// </summary>
        internal static string AssemblyHeader {
            get {
                return ResourceManager.GetString("AssemblyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking Changes.
        /// </summary>
        internal static string BreakingChanges {
            get {
                return ResourceManager.GetString("BreakingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Catalog last updated on.
        /// </summary>
        internal static string CatalogLastUpdated {
            get {
                return ResourceManager.GetString("CatalogLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DetailsPageTitle {
            get {
                return ResourceManager.GetString("DetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See &apos;https://aka.ms/dotnet-portabilityanalyzer&apos; to learn how to read this table.
        /// </summary>
        internal static string HowToReadTheExcelTable {
            get {
                return ResourceManager.GetString("HowToReadTheExcelTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing assemblies.
        /// </summary>
        internal static string MissingAssembliesPageTitle {
            get {
                return ResourceManager.GetString("MissingAssembliesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string MissingAssemblyStatus {
            get {
                return ResourceManager.GetString("MissingAssemblyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageId.
        /// </summary>
        internal static string PackageIdHeader {
            get {
                return ResourceManager.GetString("PackageIdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portability Summary.
        /// </summary>
        internal static string PortabilitySummaryPageTitle {
            get {
                return ResourceManager.GetString("PortabilitySummaryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended changes.
        /// </summary>
        internal static string RecommendedChanges {
            get {
                return ResourceManager.GetString("RecommendedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Id.
        /// </summary>
        internal static string SubmissionId {
            get {
                return ResourceManager.GetString("SubmissionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Packages.
        /// </summary>
        internal static string SupportedPackages {
            get {
                return ResourceManager.GetString("SupportedPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target member.
        /// </summary>
        internal static string TargetMemberHeader {
            get {
                return ResourceManager.GetString("TargetMemberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets.
        /// </summary>
        internal static string Targets {
            get {
                return ResourceManager.GetString("Targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target type.
        /// </summary>
        internal static string TargetTypeHeader {
            get {
                return ResourceManager.GetString("TargetTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 26 colums supported overall!!.
        /// </summary>
        internal static string TooManyColumns {
            get {
                return ResourceManager.GetString("TooManyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved assembly.
        /// </summary>
        internal static string UnresolvedUsedAssembly {
            get {
                return ResourceManager.GetString("UnresolvedUsedAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used By.
        /// </summary>
        internal static string UsedBy {
            get {
                return ResourceManager.GetString("UsedBy", resourceCulture);
            }
        }
    }
}
