//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Fx.Portability.Reports.Html.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Fx.Portability.Reports.Html.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header for assembly name entries.
        /// </summary>
        public static string AssemblyHeader {
            get {
                return ResourceManager.GetString("AssemblyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Summary.
        /// </summary>
        public static string BackToSummary {
            get {
                return ResourceManager.GetString("BackToSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that simply using a potentially broken API does not mean the app will necessarily suffer from the indicated breaking change. Many breaking changes are scoped to narrow corner-cases, and apps are only affected if they use the API in a very particular way. Breaking changes below have been grouped by scope (major, minor, or edge) depending on how likely the changes are to actually break user code in cases where the given API is used. Please read the &apos;details&apos; column to understand the particular circumstan [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BreakingChangeDisclaimer {
            get {
                return ResourceManager.GetString("BreakingChangeDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Catalog last updated on.
        /// </summary>
        public static string CatalogLastUpdated {
            get {
                return ResourceManager.GetString("CatalogLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework Compatibility.
        /// </summary>
        public static string CompatibilityPageTitle {
            get {
                return ResourceManager.GetString("CompatibilityPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate: {0}.
        /// </summary>
        public static string CouldNotLocate {
            get {
                return ResourceManager.GetString("CouldNotLocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge issues are those that will only impact a small minority of customers that use the given API in very specific ways. See issue details for more information..
        /// </summary>
        public static string EdgeCompatIssueDescription {
            get {
                return ResourceManager.GetString("EdgeCompatIssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing resources:.
        /// </summary>
        public static string ExistingResources {
            get {
                return ResourceManager.GetString("ExistingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Portability Report.
        /// </summary>
        public static string HtmlReportTitle {
            get {
                return ResourceManager.GetString("HtmlReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major issues are those that are likely to impact most customers using the given feature or API..
        /// </summary>
        public static string MajorCompatIssueDescription {
            get {
                return ResourceManager.GetString("MajorCompatIssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor issues are those that will only impact customers using the given feature in a particular way. See issue details for more information..
        /// </summary>
        public static string MinorCompatIssueDescription {
            get {
                return ResourceManager.GetString("MinorCompatIssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        public static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageId.
        /// </summary>
        public static string PackageIdHeader {
            get {
                return ResourceManager.GetString("PackageIdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portability Summary.
        /// </summary>
        public static string PortabilitySummaryPageTitle {
            get {
                return ResourceManager.GetString("PortabilitySummaryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended changes.
        /// </summary>
        public static string RecommendedChanges {
            get {
                return ResourceManager.GetString("RecommendedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retargeting compatibility issues are breaking changes that only manifest when code is targeted to run on a newer .Net Framework version. This can happen if an application does not have a &lt;a href=&quot;https://docs.microsoft.com/dotnet/api/system.runtime.versioning.targetframeworkattribute&quot;&gt;TargetFrameworkAttribute&lt;/a&gt; or when the application is rebuilt with a newer toolset..
        /// </summary>
        public static string RetargetingCompatIssueDescriptionPart1 {
            get {
                return ResourceManager.GetString("RetargetingCompatIssueDescriptionPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These issues are less impactful than runtime compatibility issues because they can typically be worked around easily, either by using a &lt;a href=&quot;https://msdn.microsoft.com/en-us/library/system.runtime.versioning.targetframeworkattribute%28v=vs.110%29.aspx&quot;&gt;TargetFrameworkAttribute&lt;/a&gt; on the assembly, using a &lt;a href=&quot;https://msdn.microsoft.com/en-us/library/bb398202.aspx&quot;&gt;TargetFrameworkVersion&lt;/a&gt; in the project file, or using older tools at build-time, depending on the particular issue. See issue details [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RetargetingCompatIssueDescriptionPart2 {
            get {
                return ResourceManager.GetString("RetargetingCompatIssueDescriptionPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retargeting compatibility issues are breaking changes that only manifest when code is targeted to run on a newer .Net Framework version. These issues are less impactful than runtime compatibility issues because they can typically be worked around easily, either by using a TargetFrameworkAttribute on the assembly, using a TargetFrameworkVersion in the project file, or using older tools at build-time, depending on the particular issue. See issue details below for more information on how these breaking changes [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RetargetingCompatIssueDescriptionPlainText {
            get {
                return ResourceManager.GetString("RetargetingCompatIssueDescriptionPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime compatibility issues are those that will occur simply by running code on a new .Net Framework version. These are the variety of breaking changes most likely to impact applications since they cannot be quirked away and do not depend on an application being recompiled..
        /// </summary>
        public static string RuntimeCompatIssueDescription {
            get {
                return ResourceManager.GetString("RuntimeCompatIssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Id.
        /// </summary>
        public static string SubmissionId {
            get {
                return ResourceManager.GetString("SubmissionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target type.
        /// </summary>
        public static string TargetTypeHeader {
            get {
                return ResourceManager.GetString("TargetTypeHeader", resourceCulture);
            }
        }
    }
}
